@startuml
title Usecase for Information system

' left to right direction

actor Користувач
actor Споживач
actor :Скульптор-споживач:

Споживач -|> Користувач 
:Скульптор-споживач:-|> Користувач 
rectangle Software {

    usecase (Переглянути інформацію)
    usecase (Авторизувати користувача)
    usecase (Отримати інформацію із рекомендацією про сон)
    usecase (Створити профіль)
    usecase (Розглянути інші профілі)
    
    (Отримати інформацію із рекомендацією про сон) .> (Авторизувати користувача) : include
    (Створити профіль) .> (Авторизувати користувача) : include
    (Розглянути інші профілі) .> (Авторизувати користувача) : include
    (Переглянути інформацію) .> (Отримати інформацію із рекомендацією про сон) : extends

    Користувач -- (Авторизувати користувача)
    Споживач -- (Отримати інформацію із рекомендацією про сон)
    :Скульптор-споживач: -- (Створити профіль)
    :Скульптор-споживач: -- (Розглянути інші профілі)

}
@enduml
