@startuml

title Cpncept Classes Diagram 

Class Користувач
Class Сповіщення
Class Розклад
Class Графік

Користувач"1" --o "1"Сповіщення: керує
Сповіщення"1" --o "+"Розклад: має
Користувач"1" --o "+"Графік: керує
@enduml
